###
GET http://localhost:8080/public/health-check

### testing api
GET http://localhost:8080/journal/id/699ecce48dee230f7dbe3887
Content-Type: application/json

{
  "username": "ram",
  "password": "ram"
}
