spring.application.name=SpringPilot

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#spring.config.import=optional:file:.env[.properties] commented for azure deployment


#For dev
#spring.data.mongodb.uri=${MONGO_URI}
#spring.data.mongodb.database=${MONGO_DB}

#For azure deployment
#spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
#spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}

#For AWS deployment
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGO_DB}

spring.data.mongodb.auto-index-creation=true
weather.api.key=${WEATHER_KEY}
secret_key=Shikhar123
#Shikhar231 this is new mongodb password
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.profiles.active=dev


# Kafka
#spring.kafka.bootstrap-servers=localhost:9092 for dev
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=weekly-sentiment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.listener.missing-topics-fatal=false

#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}



