spring:
  application:
    name: SpringPilot
  data:
    mongodb:
#      uri: ${MONGO_URI}
#      database: ${MONGO_DB}
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

anthropic:
  api-key: ${ANTHROPIC_API_KEY}