spring.application.name=SpringPilot

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.config.import=optional:file:.env[.properties]
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DB}
spring.data.mongodb.auto-index-creation=true
weather.api.key=ecde3bad8db8d549e1dc08c694c66937

#my.custom.test=HELLO_SPRING_BOOT


