spring.application.name=SpringPilot

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB}
spring.data.mongodb.auto-index-creation=true
weather.api.key=${WEATHER_KEY}
secret_key=Shikhar123

## Required connection configs for Kafka producer, consumer, and admin
#spring.kafka.properties.sasl.mechanism=PLAIN
#spring.kafka.bootstrap-servers=pkc-9q8rv.ap-south-2.aws.confluent.cloud:9092
#spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='JIALJBNBDVYQGHD4' password='cfltCEF0tZe6EhBcgWhhRb9gAyADuBE2V648n8++o89sta6lc0REGpywTGAAxvVQ';
#spring.kafka.properties.security.protocol=SASL_SSL
#
## Best practice for higher availability in Apache Kafka clients prior to 3.0
#spring.kafka.properties.session.timeout.ms=45000
#
#client.id=ccloud-springboot-client-47ac6e27-f20c-4613-ad48-0dfec493ec94


#my.custom.test=HELLO_SPRING_BOOT


